// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = NewAsset("conntrack.c", "5b4d0cb31aea17984974431d37ece520be909d3f1e2bd545282beec97cc75898")
