// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = NewAsset("conntrack.c", "89d57e41fc0db5eb06c064949a18ec33b690e36a8c5d654f1d9815e8141e227a")
