// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = NewAsset("conntrack.c", "ae30d00a7a0479eb4cc2a3482c74190c04c04bf8a5eaaa1b6850c52d8d80d9eb")
