// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var GoTls = NewRuntimeAsset("go-tls.c", "73d369adb864c676648a565c6e34729d42b1abf221f8ddfb9cbcae81513f0416")
