// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var GoTls = NewRuntimeAsset("go-tls.c", "0b8fdddf4ba625f4dc00b01e356900fa5f4f2e6170f9fe501a2328efde6ac09d")
