// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var GoTls = NewRuntimeAsset("go-tls.c", "386a095f6100cec2eb2a45164f6a3cb21af703898c85fa882ba868ff01cfd248")
