// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewRuntimeAsset("http.c", "8b23472c9608e639e8d9488e9a6e8d020d046d46e8cdf9454fd1928171006578")
