// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "80f8f0dce53d6902256ffd28c6ed49bfe139dd40c54adf756311f8866bf8f4b6")
