// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "11e3071e398b6cc2aa04e2840a96e9895c15c52ffa81e15e5aaae3e5d0c99c23")
