// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var OomKill = NewAsset("oom-kill.c", "0c4650432fc7eafd1ccd36efc0d148265388f310f72e1cf72fd88ea1e8dd7caa")
