// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewAsset("runtime-security.c", "58e57b66503119adfe2e76e5158f0e532f4fbe6cedb7a8e3503755e0463179c9")
