// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = newAsset("runtime-security.c", "bad9448d20b710e425cfe21c6f62b15d233a2b92fb1cfc41d5e96e1516c83676")
