// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = newAsset("runtime-security.c", "c53af673adbed089f62f48ad771475443649dee52469c9be557c474a4d858a24")
