// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var TcpQueueLength = NewAsset("tcp-queue-length.c", "690211a2c3260207545a3dd26959b542a2a3a72c69a1b3b49d73dbef44c2f04d")
