// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "d050474eb0eb3070e251d1396e69e844f733a6c59308a3d08444fbb61d277ac0")
