// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = NewAsset("tracer.c", "673aa0649883122c75a7b755dd0f7524462a83605c23919deb8724262b0e5b46")
