// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = NewAsset("tracer.c", "f1d9a726c5097a970c31755f5ab5cc43c8e83e084cdab1fadf1a1159dfefe19f")
